### ISSUE TITLE
artisan command

### ISSUE THREAD

**Issue by ruzrulit** [ignasbernotas/laravel-model-generator#19]
Hello dear Sir,

I have an issue running the command: 
`php artisan make:models`
It says: undefined variable: tables
I've looked in the MakeModelsCommand class, on that moment when it runs getSchemaTables function, the env('DB_CONNECTION') is undefined.
Could you please help me?

With kind regards,
Ruzalin

**Comment by ruzrulit** [comment]
i have changed manually .env file and it works fine. But can we solve this issue without this change?

**Comment by iberflow** [comment]
Fixed it with 1.1.2 release.

**Comment by arncore** [comment]
This issue seems to be happening still. The DB_CONNECTION is fine but the db config which I set myself in app/config/database.php is not obtained but instead the one in .env is used. 

In turn I get errors such as:

  [Illuminate\Database\QueryException]
  SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES) (SQL: SELECT table_name A
  S name FROM information_schema.tables WHERE table_type='BASE TABLE' AND table_schema = 'homestead')

SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES)

Again, I have modified my db config in app/config/database.php and this should not be happening. Maybe I am missing something?

Thanks.

EDIT:
I also solved this issue by modifying .env myself.
